package com.testapp.entities

data class Image(
    val id: Int = 0,
    val pageURL: String = "",
    val type: String = "",
    val tags: List<String> = emptyList(),
    val previewURL: String = "",
    val previewWidth: Int = 0,
    val previewHeight: Int = 0,
    val webFormatURL: String = "",
    val webFormatWidth: Int = 0,
    val webFormatHeight: Int = 0,
    val largeImageURL: String = "",
    val imageWidth: Int = 0,
    val imageHeight: Int = 0,
    val imageSize: Int = 0,
    val views: Int = 0,
    val downloads: Int = 0,
    val collections: Int = 0,
    val likes: Int = 0,
    val comments: Int = 0,
    val userId: Int = 0,
    val user: String = "",
    val userImageURL: String = "",
)